language: scala
scala:
- 2.12.2
jdk:
- oraclejdk8
script:
- sbt clean coverage test
notifications:
  irc: irc.freenode.org#cilib
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/9df9c83ef091cee2f675
    on_success: always
    on_failure: always
    on_start: false
after_success:
- pip install --user codecov && codecov
# - "[[ $TRAVIS_BRANCH == \"master\" ]] && { travis_wait 60 sbt publish; };"
branches:
  only:
    - master
